name: Download DDColor Models
on: workflow_dispatch

jobs:
  download_files:
    runs-on: ubuntu-latest
    steps:
    - name: Clone OpenVINO Repository via Git LFS
      run: |
        # Включаем поддержку больших файлов
        git lfs install
        
        # Клонируем только нужную папку с моделью (без лишнего мусора)
        git clone --depth 1 --filter=blob:none --sparse https://github.com
        cd openvino_notebooks
        git sparse-checkout set notebooks/ddcolor-image-colorization
        
        # Принудительно выкачиваем оригинальные тяжелые .bin и .xml файлы
        git lfs pull
        
        # Переносим файлы в отдельную папку для отправки
        mkdir ../models
        cp notebooks/ddcolor-image-colorization/ddcolor.xml ../models/
        cp notebooks/ddcolor-image-colorization/ddcolor.bin ../models/

    - name: Check file sizes
      run: |
        ls -lh models/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ddcolor-openvino-fp16
        path: models/
