name: Download DDColor Models
on: workflow_dispatch

jobs:
  download_files:
    runs-on: ubuntu-latest
    steps:
    - name: Download from HF Mirror
      run: |
        mkdir models
        cd models
        # Скачиваем через проверенное и незаблокированное зеркало, где лежат оригинальные FP16 файлы
        curl -L "https://hf-mirror.com" -o ddcolor.xml
        curl -L "https://hf-mirror.com" -o ddcolor.bin
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ddcolor-openvino-fp16
        path: models/
