name: Download DDColor Models
on: workflow_dispatch

jobs:
  download_files:
    runs-on: ubuntu-latest
    steps:
    - name: Download from Intel Storage
      run: |
        mkdir models
        cd models
        curl -L "https://openvinotoolkit.org" -o ddcolor.xml
        curl -L "https://openvinotoolkit.org" -o ddcolor.bin
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ddcolor-openvino-fp16
        path: models/
